"""One module per supported ATS platform, each exporting a single ADAPTER
(see base.AtsAdapter). ADAPTERS below is the registry every platform gets
collected into — the only thing app.services.ats_adapters needs to build
its public detect/list functions on top of.
"""

from app.services.adapters import (
    adp,
    amazon,
    apple,
    ashby,
    attrax,
    avature,
    bamboohr,
    bestbuy,
    breezyhr,
    clearcompany,
    clinch,
    csod,
    dynatrace,
    echo_jobs,
    eightfold,
    fullstack,
    gem,
    glidefast,
    google,
    greenhouse,
    gupy,
    hirehive,
    hiringroom,
    icims,
    jazzhr,
    lever,
    linecorp,
    motion_recruitment,
    nlx,
    oracle_fusion,
    paradox,
    paycor_recruiting,
    peopleadmin,
    personio,
    phenom,
    pinpoint,
    recruitee,
    rippling,
    sportsmans_warehouse,
    stripe,
    successfactors,
    taleo,
    talemetry,
    talentbrew,
    talentreef,
    toss,
    walmart,
    workable,
    workday,
    zenats,
)
from app.services.adapters.base import AtsAdapter

ADAPTERS: list[AtsAdapter] = [
    greenhouse.ADAPTER,
    lever.ADAPTER,
    ashby.ADAPTER,
    gem.ADAPTER,
    bamboohr.ADAPTER,
    personio.ADAPTER,
    workday.ADAPTER,
    jazzhr.ADAPTER,
    recruitee.ADAPTER,
    breezyhr.ADAPTER,
    workable.ADAPTER,
    adp.ADAPTER,
    amazon.ADAPTER,
    google.ADAPTER,
    apple.ADAPTER,
    walmart.ADAPTER,
    bestbuy.ADAPTER,
    linecorp.ADAPTER,
    toss.ADAPTER,
    fullstack.ADAPTER,
    motion_recruitment.ADAPTER,
    oracle_fusion.ADAPTER,
    # Ahead of clinch: clinch's embedded_match fallback (any sitemap.xml
    # with /jobs/ paths) false-positives on iCIMS/Jibe tenants whose own
    # unrelated site sitemap happens to list /jobs/{id} detail pages
    # (verified live: careers.mheducation.com) — icims's stricter
    # jibecdn.com/.icims.com signature check should get first refusal.
    icims.ADAPTER,
    clinch.ADAPTER,
    clearcompany.ADAPTER,
    echo_jobs.ADAPTER,
    talentbrew.ADAPTER,
    eightfold.ADAPTER,
    nlx.ADAPTER,
    stripe.ADAPTER,
    dynatrace.ADAPTER,
    glidefast.ADAPTER,
    paycor_recruiting.ADAPTER,
    successfactors.ADAPTER,
    attrax.ADAPTER,
    phenom.ADAPTER,
    avature.ADAPTER,
    paradox.ADAPTER,
    gupy.ADAPTER,
    hirehive.ADAPTER,
    peopleadmin.ADAPTER,
    pinpoint.ADAPTER,
    zenats.ADAPTER,
    talemetry.ADAPTER,
    csod.ADAPTER,
    hiringroom.ADAPTER,
    taleo.ADAPTER,
    rippling.ADAPTER,
    talentreef.ADAPTER,
    sportsmans_warehouse.ADAPTER,
]
