"""One module per supported ATS platform, each exporting a single ADAPTER
(see base.AtsAdapter). ADAPTERS below is the registry every platform gets
collected into — the only thing app.services.ats_adapters needs to build
its public detect/list functions on top of.
"""

from app.services.adapters import (
    adp,
    amazon,
    apple,
    applitrack,
    applicantpro,
    ashby,
    attrax,
    avature,
    bamboohr,
    bestbuy,
    canyons,
    breezyhr,
    clearcompany,
    clinch,
    comeet,
    csod,
    dayforce,
    dynatrace,
    echo_jobs,
    eightfold,
    flyio,
    fullstack,
    gem,
    glidefast,
    google,
    greenhouse,
    gupy,
    happydance,
    hirehive,
    hiringroom,
    homerun,
    icims,
    intuitive,
    jazzhr,
    jobaps,
    jobvite,
    join,
    lever,
    linecorp,
    motion_recruitment,
    nlx,
    oracle_fusion,
    paradox,
    paycor_recruiting,
    paylocity,
    peopleadmin,
    personio,
    phenom,
    pinpoint,
    recruitee,
    rcwilley,
    rippling,
    schoolspring,
    selectminds,
    smartrecruiters,
    sportsmans_warehouse,
    stripe,
    successfactors,
    suu,
    taleo,
    talemetry,
    talentbrew,
    talentreef,
    toss,
    ultipro,
    valve,
    walmart,
    workable,
    workday,
    workforce_ready,
    zenats,
)
from app.services.adapters.base import AtsAdapter

ADAPTERS: list[AtsAdapter] = [
    greenhouse.ADAPTER,
    lever.ADAPTER,
    ashby.ADAPTER,
    gem.ADAPTER,
    bamboohr.ADAPTER,
    personio.ADAPTER,
    workday.ADAPTER,
    smartrecruiters.ADAPTER,
    jazzhr.ADAPTER,
    applicantpro.ADAPTER,
    jobvite.ADAPTER,
    join.ADAPTER,
    homerun.ADAPTER,
    jobaps.ADAPTER,
    recruitee.ADAPTER,
    breezyhr.ADAPTER,
    workable.ADAPTER,
    adp.ADAPTER,
    amazon.ADAPTER,
    google.ADAPTER,
    apple.ADAPTER,
    intuitive.ADAPTER,
    flyio.ADAPTER,
    valve.ADAPTER,
    walmart.ADAPTER,
    bestbuy.ADAPTER,
    linecorp.ADAPTER,
    toss.ADAPTER,
    fullstack.ADAPTER,
    motion_recruitment.ADAPTER,
    oracle_fusion.ADAPTER,
    # Ahead of clinch: clinch's embedded_match fallback (any sitemap.xml
    # with /jobs/ paths) false-positives on iCIMS/Jibe tenants whose own
    # unrelated site sitemap happens to list /jobs/{id} detail pages
    # (verified live: careers.mheducation.com) — icims's stricter
    # jibecdn.com/.icims.com signature check should get first refusal.
    icims.ADAPTER,
    clinch.ADAPTER,
    clearcompany.ADAPTER,
    comeet.ADAPTER,
    echo_jobs.ADAPTER,
    talentbrew.ADAPTER,
    eightfold.ADAPTER,
    nlx.ADAPTER,
    stripe.ADAPTER,
    dynatrace.ADAPTER,
    glidefast.ADAPTER,
    paycor_recruiting.ADAPTER,
    paylocity.ADAPTER,
    dayforce.ADAPTER,
    successfactors.ADAPTER,
    attrax.ADAPTER,
    phenom.ADAPTER,
    # Sitemap-fallback embedded_match reasoning is the same as clinch's
    # (see the note above icims.ADAPTER) — no observed collision candidate
    # yet, placed with the other white-label CMS adapters regardless.
    happydance.ADAPTER,
    avature.ADAPTER,
    paradox.ADAPTER,
    gupy.ADAPTER,
    hirehive.ADAPTER,
    peopleadmin.ADAPTER,
    applitrack.ADAPTER,
    schoolspring.ADAPTER,
    pinpoint.ADAPTER,
    zenats.ADAPTER,
    talemetry.ADAPTER,
    csod.ADAPTER,
    hiringroom.ADAPTER,
    taleo.ADAPTER,
    rippling.ADAPTER,
    talentreef.ADAPTER,
    sportsmans_warehouse.ADAPTER,
    rcwilley.ADAPTER,
    suu.ADAPTER,
    canyons.ADAPTER,
    ultipro.ADAPTER,
    workforce_ready.ADAPTER,
    selectminds.ADAPTER,
]
