"""resume upload, review, scoring, tailored generation

Revision ID: 55bbd81c14d1
Revises: 4d5651ec6f16
Create Date: 2026-09-11 16:07:03.685904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55bbd81c14d1'
down_revision: Union[str, Sequence[str], None] = '4d5651ec6f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index('uq_resumes_one_main_per_user', 'resumes', ['user_id'], unique=True, postgresql_where=sa.text('is_main'))
    op.create_table('resume_reviews',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_reviews_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_reviews'))
    )
    op.create_index(op.f('ix_resume_reviews_resume_id'), 'resume_reviews', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_reviews_user_id'), 'resume_reviews', ['user_id'], unique=False)
    op.create_table('resume_scores',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_resume_scores_job_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_scores_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_scores'))
    )
    op.create_index(op.f('ix_resume_scores_job_posting_id'), 'resume_scores', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_resume_scores_resume_id'), 'resume_scores', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_scores_user_id'), 'resume_scores', ['user_id'], unique=False)
    op.create_table('tailored_resumes',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_tailored_resumes_job_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_tailored_resumes_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tailored_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tailored_resumes'))
    )
    op.create_index(op.f('ix_tailored_resumes_job_posting_id'), 'tailored_resumes', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_resume_id'), 'tailored_resumes', ['resume_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_user_id'), 'tailored_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_user_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_resume_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_job_posting_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index(op.f('ix_resume_scores_user_id'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_resume_id'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_job_posting_id'), table_name='resume_scores')
    op.drop_table('resume_scores')
    op.drop_index(op.f('ix_resume_reviews_user_id'), table_name='resume_reviews')
    op.drop_index(op.f('ix_resume_reviews_resume_id'), table_name='resume_reviews')
    op.drop_table('resume_reviews')
    op.drop_index('uq_resumes_one_main_per_user', table_name='resumes', postgresql_where=sa.text('is_main'))
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
