"""resume score category breakdown

Revision ID: 55d3a6b16601
Revises: 9150f916b6db
Create Date: 2026-09-23 09:13:50.587572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d3a6b16601'
down_revision: Union[str, Sequence[str], None] = '9150f916b6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'resume_scores',
        sa.Column(
            'category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        'tailored_resume_scores',
        sa.Column(
            'category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_resume_scores', 'category_scores')
    op.drop_column('resume_scores', 'category_scores')
    # ### end Alembic commands ###
