"""index job_posting title_key

Revision ID: 994faf52aead
Revises: 00ba02dcdf61
Create Date: 2026-09-22 15:19:50.493271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994faf52aead'
down_revision: Union[str, Sequence[str], None] = '00ba02dcdf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_postings_title_key'), 'job_postings', ['title_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_title_key'), table_name='job_postings')
    # ### end Alembic commands ###
