"""resume skill additions

Revision ID: a2896c292c76
Revises: bab50b259bde
Create Date: 2026-09-24 14:25:37.126906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2896c292c76'
down_revision: Union[str, Sequence[str], None] = 'bab50b259bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_skill_additions',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_skill_additions_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_skill_additions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_skill_additions')),
    sa.UniqueConstraint('resume_id', 'keyword', name='uq_resume_skill_additions_resume_keyword')
    )
    op.create_index(op.f('ix_resume_skill_additions_resume_id'), 'resume_skill_additions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skill_additions_user_id'), 'resume_skill_additions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_skill_additions_user_id'), table_name='resume_skill_additions')
    op.drop_index(op.f('ix_resume_skill_additions_resume_id'), table_name='resume_skill_additions')
    op.drop_table('resume_skill_additions')
    # ### end Alembic commands ###
