"""latest artifact pointers on applications

Revision ID: aa6b02cf4f64
Revises: 51692733dae8
Create Date: 2026-09-13 13:50:51.995171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6b02cf4f64'
down_revision: Union[str, Sequence[str], None] = '51692733dae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_job_applications', sa.Column('latest_score_id', sa.UUID(), nullable=True))
    op.add_column('user_job_applications', sa.Column('latest_tailored_resume_id', sa.UUID(), nullable=True))
    op.add_column('user_job_applications', sa.Column('latest_cover_letter_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_user_job_applications_latest_tailored_resume_id_tailored_resumes'), 'user_job_applications', 'tailored_resumes', ['latest_tailored_resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_job_applications_latest_cover_letter_id_cover_letters'), 'user_job_applications', 'cover_letters', ['latest_cover_letter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_job_applications_latest_score_id_resume_scores'), 'user_job_applications', 'resume_scores', ['latest_score_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Backfill: point every existing application at whichever score/tailored
    # resume/cover letter was most recently generated for that (user, job)
    # pair, so history predating this column isn't invisible until the next
    # regeneration.
    op.execute("""
        UPDATE user_job_applications uja
        SET latest_score_id = latest.id
        FROM (
            SELECT DISTINCT ON (user_id, job_posting_id) id, user_id, job_posting_id
            FROM resume_scores
            ORDER BY user_id, job_posting_id, created_at DESC
        ) latest
        WHERE uja.user_id = latest.user_id AND uja.job_posting_id = latest.job_posting_id
    """)
    op.execute("""
        UPDATE user_job_applications uja
        SET latest_tailored_resume_id = latest.id
        FROM (
            SELECT DISTINCT ON (user_id, job_posting_id) id, user_id, job_posting_id
            FROM tailored_resumes
            ORDER BY user_id, job_posting_id, created_at DESC
        ) latest
        WHERE uja.user_id = latest.user_id AND uja.job_posting_id = latest.job_posting_id
    """)
    op.execute("""
        UPDATE user_job_applications uja
        SET latest_cover_letter_id = latest.id
        FROM (
            SELECT DISTINCT ON (user_id, job_posting_id) id, user_id, job_posting_id
            FROM cover_letters
            ORDER BY user_id, job_posting_id, created_at DESC
        ) latest
        WHERE uja.user_id = latest.user_id AND uja.job_posting_id = latest.job_posting_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_job_applications_latest_score_id_resume_scores'), 'user_job_applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_job_applications_latest_cover_letter_id_cover_letters'), 'user_job_applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_job_applications_latest_tailored_resume_id_tailored_resumes'), 'user_job_applications', type_='foreignkey')
    op.drop_column('user_job_applications', 'latest_cover_letter_id')
    op.drop_column('user_job_applications', 'latest_tailored_resume_id')
    op.drop_column('user_job_applications', 'latest_score_id')
    # ### end Alembic commands ###
