"""archive applications

Revision ID: c752b41f99ef
Revises: aa6b02cf4f64
Create Date: 2026-09-13 14:06:50.322753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c752b41f99ef'
down_revision: Union[str, Sequence[str], None] = 'aa6b02cf4f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_job_applications',
        sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_job_applications', 'is_archived')
    # ### end Alembic commands ###
