"""resume score overqualification note

Revision ID: d6bd605f3a81
Revises: 55d3a6b16601
Create Date: 2026-09-23 10:47:52.293800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bd605f3a81'
down_revision: Union[str, Sequence[str], None] = '55d3a6b16601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'resume_scores',
        sa.Column('overqualification_note', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'tailored_resume_scores',
        sa.Column('overqualification_note', sa.Text(), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_resume_scores', 'overqualification_note')
    op.drop_column('resume_scores', 'overqualification_note')
    # ### end Alembic commands ###
